### ISSUE TITLE
Can't install on CentOS 7

### ISSUE THREAD

**Issue by pddg** [pddg/ansible-role-xkeysnail#6]
```bash
$ docker run --rm -it centos:7 /bin/bash
[centos] $ yum update -y
[centos] $ yum install -y https://centos7.iuscommunity.org/ius-release.rpm
[centos] $ yum install -y pytho36u python36u-pip python36u-devel
[centos] $ pip3.6 install xkeysnail
Collecting xkeysnail
  Using cached https://files.pythonhosted.org/packages/04/90/2f25f4387d8e0fa556ee7c42644c4d7900c9679887d7ff4ec66a5d728af0/xkeysnail-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-87xqbccp/xkeysnail/setup.py", line 4, in <module>
        exec(open("xkeysnail/info.py").read())
      File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 63: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-87xqbccp/xkeysnail/
```

Why this happen?

**Comment by pddg** [comment]
This reproduce in Ubuntu:16.04 LTS. 
Docker cause this error?
